: Build and release Aseprite

:
:
:
      - 主
:
      - 'BuildLog.md'
:
:
：发布

:
:
: Fetch deps info
: ubuntu-latest
:
: ${{ steps.aseprite-link.outputs.download-link }}
: ${{ steps.aseprite-link.outputs.release-tag }}
    步骤:
      - 名称: 获取 Aseprite 发布链接
        ID: aseprite-link
：a1393323447/fetch-release@main
:
：aseprite
：aseprite
：Aseprite-.*?-Source.zip

:
    name: 创建发布
: ubuntu-latest
    needs: 获取-阿斯普赖特信息
:
      内容: 写入
:
: ${{ needs.fetch-aseprite-info.outputs.download-link }}
      release-tag: ${{ needs.fetch-aseprite-info.outputs.release-tag }}
    步骤:
      - 使用: actions/checkout@v2

        with:
: ${ needs.fetch-aseprite-info.outputs.release-tag }}
          正文: Aseprite-${{ needs.fetch-aseprite-info.outputs.release-tag }}
          skipIfReleaseExists: true
          token: ${{ secrets.GITHUB_TOKEN }}

  build-aseprite:
    name: Build Aseprite
create-release
    权限:
      内容: 写入
运行于${ matrix.os }}
    策略:
        矩阵:
          操作系统: [ windows-latest ]
        快速失败: 假
    步骤:
      - 名称: 安装依赖项
        如果: runner.os == 'Linux'
        shell: bash
        运行: |
          sudo apt-get update -qq
          sudo apt-get install -y \
            libpixman-1-dev libfreetype6-dev libharfbuzz-dev zlib1g-dev \
            libx11-dev libxcursor-dev libxi-dev libxrandr-dev libgl1-mesa-dev \
            libfontconfig1-dev
      - uses: actions/checkout@v4
      - 名称: 安装 Aseprite
        shell: bash
        运行: |
          git clone --recurse-submodules -j8 https://github.com/aseprite/aseprite --branch ${{ needs.create-release.outputs.release-tag }}
      - 名称: 安装 Skia
工作目录: aseprite
        shell: bash
        运行: |
          如果 [[ "${{ runner.os }}" == "Windows" ]] ; 则
            choco install wget -y --no-progress
            wget https://github.com/aseprite/skia/releases/download/m124-08a5439a6b/Skia-Windows-Release-x64.zip
            unzip Skia-Windows-Release-x64.zip -d skia
          elif [[ "${{ runner.os }}" == "macOS" ]] ; then
            wget https://github.com/aseprite/skia/releases/download/m124-08a5439a6b/Skia-macOS-Release-arm64.zip
            将 Skia-macOS-Release-arm64.zip 解压到 skia 目录
          否则
            使用 wget 下载 https://github.com/aseprite/skia/releases/download/m124-08a5439a6b/Skia-Linux-Release-x64.zip
            解压 Skia-Linux-Release-x64.zip 到 skia 目录
          fi
      - uses: aseprite/get-ninja@main
      - 使用: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'
      - name: Generating Makefiles
        shell: bash
工作目录: aseprite
        运行: |
          export enable_ccache=off
          export laf_backend=skia
          export enable_scripting=on

          if [[ "${{ runner.os }}" == "macOS" ]] ; then
            export skia_arch=arm64
          否则
            export skia_arch=x64
          fi

          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 \
            -DENABLE_TESTS=OFF \
            -DENABLE_SCRIPTING=$enable_scripting \
            -DENABLE_CCACHE=$enable_ccache \
            -DLAF_BACKEND=$laf_backend \
            -DSKIA_DIR=$(realpath skia) \
            -DOPENSSL_USE_STATIC_LIBS=ON \
            -DSKIA_LIBRARY_DIR=$(realpath skia/out/Release-$skia_arch)
      - name: Compiling
        shell: bash
        working-directory: aseprite
        run: |
          cd build && ninja
      - name: Clean Up Build folder
        working-directory: aseprite/build/bin
        shell: bash
        run: find . -mindepth 1 ! \( -name 'aseprite' -o -name 'aseprite.exe' -o -name 'data' -prune -o -name 'Aseprite.app' -prune \) -exec rm -rf {} +
      - name: Make portable zip
        working-directory: aseprite/build/bin
        run: echo '# This file is here so Aseprite behaves as a portable program' > aseprite.ini
      - name: Create release
        working-directory: aseprite/build/bin
        run: 7z -tzip a Aseprite-${{ needs.create-release.outputs.release-tag }}-${{ runner.os }}.zip *
      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: aseprite/build/bin/Aseprite-${{ needs.create-release.outputs.release-tag }}-${{ runner.os }}.zip
          asset_name: Aseprite-${{ needs.create-release.outputs.release-tag }}-${{ runner.os }}.zip
          tag: ${{ needs.create-release.outputs.release-tag }}
